Manipulate list features
M0rrighan/To-do-list pull request #4
Opened 2021-09-24 16:15 UTC by M0rrighan

## Milestone 3 - add & remove

### Followed requirements: 

- Remove all hardcoded items from the tasks array.
- Create a new JavaScript file for the new functionality.
- Implement a function for adding a new task (add a new element to the array).
- Implement a function for editing task descriptions.
- Implement a function for deleting a task (remove an element from the array).
- Implement a function for the "Clear all completed" button (use filter() method).
- By default new tasks should have the property completed set to false and the property index set to the value of the new array length (i.e. if you're adding a 5th task to the list, the index of that task should equal to 5).
- Deleting a task should update all remaining items' indexes, so they represent the current list order and are unique.
- All changes to the To Do List should be saved in local storage.

2021-09-24 17:04 UTC, helman101 requested changes
# STATUS: CHANGES REQUIRED ♻️ 🔴 

Hi @M0rrighan  👋, 

You have done an excellent job working on this project 👏 👏👏
but there are still some requirements which aren't been addressed yet.

## To Highlight 🌟 
- You had done a great job passing all the linters.
- You had done a good job with your README file. 
- You had implemented the required new functions successfully. 🤩 

 ## Required Changes ♻️
We are almost there, but in order to complete this part and go ahead with the next project, you have to fix a couple of issues:

- [ ] Please check the comments below 🚀 

## Optional Changes 🤓 
Take a look at these [OPTIONAL] changes to improve your project:

- [ ] please check the comments below for [OPTIONAL] changes

Cheers and Happy coding!👏👏👏

![fire](https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif)

If anything is not 100% clear please leave your questions or comments in the PR thread, we will be glad to help you 😄.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-24 17:04 UTC, helman101 commented on src/list.js
> +  }
- [ ] You have done a wonderful job with the new functionality, but as the project requirements say, you should put this on a new Javascript file 🤓 
    - Kindly move this to another Javascript file, and you will be good to go 😄
    ![image](https://user-images.githubusercontent.com/60789317/134711614-92219608-4ec2-4ae1-a5e3-6a1eb81dc202.png)

2021-09-24 17:04 UTC, helman101 commented on src/list.js
> +  }
- [ ] [OPTIONAL] There is an issue when removing a single element, whenever I have 2 tasks and I select the last one and then the first one and delete the first one, both tasks disappear. 🤨 
    - Here is a gif to show you exactly what happens. 🚀 
    ![issue](https://user-images.githubusercontent.com/60789317/134713407-ec306b01-dd3a-4d3d-a290-9043f2b6cfbb.gif)

2021-09-25 20:09 UTC, carlos-ssh approved these changes
Hi @M0rrighan , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-25 20:18 UTC, merged